services:
  web:
    env_file:
      - .env
    build: 
        context: ./
        dockerfile: ./docker/web/Dockerfile
    container_name: videoreview-web
    ports:
      - "3489:3489"
    environment:
      DATABASE_URL: postgres://videoreview:videoreview@db:5432/videoreview
      NEXT_PUBLIC_VIDEO_REVIEW_TITLE: VideoReview
      NEXT_PUBLIC_VIDEO_REVIEW_DESC: Lightweight video review tool
      JWT_SECRET: local-dev-secret
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: videoreview-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: videoreview
      POSTGRES_PASSWORD: videoreview
      POSTGRES_DB: videoreview
    volumes:
      - pgdata:/var/lib/postgresql/data

  localstack:
      env_file:
        - .env
      image: localstack/localstack:latest
      container_name: "videoreview-localstack"
      depends_on:
          - web
      ports:
          - "4566:4566"
      environment:
          # https://docs.localstack.cloud/references/configuration/
          - DEBUG=${DEBUG:-0}
          - LAMBDA_KEEPALIVE_MS=2592000000 # 30 days
      volumes:
          - ./docker/localstack:/etc/localstack/init/ready.d

volumes:
  pgdata:
